services:
  _defaults:
    autowire: true
    autoconfigure: true

  AgantarCom\CalendarBundle\Service\CalendarService: ~
  AgantarCom\CalendarBundle\Model\CalendarEvent: ~
  AgantarCom\CalendarBundle\Twig\CalendarBundleExtension:
    tags:
      - { name: twig.extension }
